Repository Song-s-PaaSTA/Plog-Android, pull requests merged in 2024-09, with the labels that each got.

#34 [Feature/#33] : 최근 플로깅 루트 UI 구현
  app/src/main/java/com/kpaas/plog/domain/entity/MyPloggingListEntity.kt
  app/src/main/java/com/kpaas/plog/presentation/navigator/PlogNavHost.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/navigation/PloggingNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/MyPloggingScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/MyPloggingViewModel.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/navigation/ProfileNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/screen/ProfileScreen.kt
  app/src/main/res/drawable/ic_my_plogging_down_arrow.xml
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], 🐱 가을

#38 [Feature/#37] 신고 수정하기 상태 버튼 로직 수정 & 백스택 수정
  app/src/main/java/com/kpaas/plog/presentation/report/navigation/ReportNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportModifyScreen.kt
Labels: ♻️ [REFACTOR], 🐱 가을

#40 [Feature/#39] : 플로깅 시간 1분 미만일 때 다이얼로그 띄우기
  app/src/main/java/com/kpaas/plog/core_ui/component/PlogDialog.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/button/ProgressButton.kt
  app/src/main/java/com/kpaas/plog/domain/entity/ReportContentEntity.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/CertificationScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/PloggingScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/screen/ProfileScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/MyReportScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportContentScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportModifyScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportViewModel.kt
  app/src/main/res/drawable/ic_report_bookmark_selected.xml
  app/src/main/res/drawable/ic_report_bookmark_unselected.xml
  app/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 🐱 가을

#42 [Feature/#41] : 검색 페이지 UI 구현
  app/build.gradle.kts
  app/src/main/java/com/kpaas/plog/app/di/RoomModule.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/SearchTextField.kt
  app/src/main/java/com/kpaas/plog/data_local/LocalDatabase.kt
  app/src/main/java/com/kpaas/plog/data_local/dao/RecentKeywordDao.kt
  app/src/main/java/com/kpaas/plog/data_local/entity/RecentKeywordEntity.kt
  app/src/main/java/com/kpaas/plog/data_local/repository/RecentKeywordRepository.kt
  app/src/main/java/com/kpaas/plog/domain/entity/SearchResultListEntity.kt
  app/src/main/java/com/kpaas/plog/presentation/main/MainActivity.kt
  app/src/main/java/com/kpaas/plog/presentation/main/navigation/MainNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/main/screen/MainScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/navigator/PlogNavHost.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/navigation/PloggingNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/navigation/PloggingNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/PloggingScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/navigation/ReportNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/report/navigation/ReportNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportWriteScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/search/navigation/SearchNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/search/navigation/SearchNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/search/screen/RecentKeywordScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/search/screen/SearchResultScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/search/screen/SearchScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/search/screen/SearchViewModel.kt
  app/src/main/res/drawable/ic_search_delete.xml
  app/src/main/res/drawable/ic_search_logo.png
  app/src/main/res/drawable/ic_search_pin.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 💟 [UI], ⭐ [FEAT], 🐱 가을

#46 [Feature/#43] : 신고 게시물 필터링 구현
  app/src/main/java/com/kpaas/plog/core_ui/component/chip/FilterChipItem.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/chip/ReportChipItem.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/dialog/PlogDialog.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/textfield/SearchTextField.kt
  app/src/main/java/com/kpaas/plog/presentation/main/screen/MainScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/PloggingScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/screen/ProfileScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/MyReportScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportViewModel.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportWriteScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/search/screen/SearchScreen.kt
  app/src/main/java/com/kpaas/plog/util/BottomNavigationItem.kt
  app/src/main/java/com/kpaas/plog/util/ChipState.kt
  app/src/main/res/drawable/ic_report_toggle.xml
Labels: 💟 [UI], ⭐ [FEAT], 🐱 가을

#45 [FEAT/#44] 북마크 UI 구현
  app/src/main/java/com/kpaas/plog/domain/entity/BookmarkEntity.kt
  app/src/main/java/com/kpaas/plog/presentation/navigator/PlogNavHost.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/navigation/ProfileNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/screen/ProfileScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/navigation/ReportNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/BookmarkScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/BookmarkViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], 🐰 윤지

#52 [Feature/#51] : 플로깅 루트 추천 플로우 수정
  app/src/main/java/com/kpaas/plog/core_ui/theme/Color.kt
  app/src/main/java/com/kpaas/plog/data/datasourceimpl/PloggingPreferencesDataSourceImpl.kt
  app/src/main/java/com/kpaas/plog/presentation/map/screen/MapScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/PloggingScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/viewmodel/PloggingViewModel.kt
  app/src/main/res/drawable/ic_map_marker.xml
  app/src/main/res/values/strings.xml
Labels: ➕ [ADD], ✅ [MOD], 🐱 가을

#56 [Feature/#55] 신고 게시물 필터(최신순, 인기순) 중복 방지
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/viewmodel/ReportViewModel.kt
Labels: ✅ [MOD], 🐰 윤지
