Repository Song-s-PaaSTA/Plog-Android, pull requests merged in 2024-08, with the labels that each got.

#6 [Feature/#4] : 버튼 컴포넌트 만들기
  app/src/main/java/com/kpaas/plog/core_ui/component/button/PlogAuthButton.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/button/PlogBottomButton.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/button/ProgressButton.kt
Labels: 💟 [UI], ⭐ [FEAT], 🐱 가을

#9 [Feature/#8] : 회원가입 페이지 UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kpaas/plog/presentation/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/LoginScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/SignupScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/navigator/PlogNavHost.kt
  app/src/main/java/com/kpaas/plog/util/ContextExt.kt
  app/src/main/res/drawable/ic_signup_camera.xml
  app/src/main/res/drawable/ic_signup_profile.xml
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], ⭐ [FEAT], 🐱 가을

#11 [Feature/#10] : 플로깅 페이지 UI 구현 & 네이버 지도 API 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kpaas/plog/PlogApp.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/SearchTextField.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/button/PlogBottomButton.kt
  app/src/main/java/com/kpaas/plog/presentation/map/screen/MapScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/ExampleScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/PloggingScreen.kt
  app/src/main/res/drawable/ic_plogging_search.xml
  app/src/main/res/values/strings.xml
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 💟 [UI], ⭐ [FEAT], 🐱 가을

#14 [Feature/#12] : GPS&사진인증 UI 구현
  app/src/main/java/com/kpaas/plog/presentation/navigator/PlogNavHost.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/navigation/PloggingNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/navigation/PloggingNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/CertificationScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/PloggingScreen.kt
  app/src/main/java/com/kpaas/plog/util/CalculateTimeDifference.kt
  app/src/main/res/drawable/ic_plogging_camera.xml
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], ⭐ [FEAT], 🐱 가을

#15 [Feature/#13] : 쓰레기 지도 마커 캡션 기능 구현
  app/src/main/java/com/kpaas/plog/domain/entity/MarkerEntity.kt
  app/src/main/java/com/kpaas/plog/presentation/map/screen/MapScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/PloggingScreen.kt
Labels: 💟 [UI], ⭐ [FEAT], 🐱 가을

#18 [Feature/#16] : 신고 페이지 UI 구현
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/main/java/com/kpaas/plog/domain/entity/ReportContentEntity.kt
  app/src/main/java/com/kpaas/plog/domain/entity/ReportListEntity.kt
  app/src/main/java/com/kpaas/plog/presentation/navigator/PlogNavHost.kt
  app/src/main/java/com/kpaas/plog/presentation/report/navigation/ReportNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/report/navigation/ReportNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportContentScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportViewModel.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportWriteScreen.kt
  app/src/main/res/drawable/ic_appbar_close.xml
  app/src/main/res/drawable/ic_report_bookmark.xml
  app/src/main/res/drawable/ic_report_fab.xml
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], ⭐ [FEAT], 🐱 가을

#20 [Feature/#17] : 마이페이지 UI 구현
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  app/src/main/java/com/kpaas/plog/presentation/profile/screen/ProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], 🐰 윤지

#21 [Feature/#19] : 카카오 로그인 API 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kpaas/plog/PlogApp.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/LoginScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/LoginViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ⭐ [FEAT], 🐱 가을

#23 [Feature/#22] : 네이버 로그인 API 연동
  app/build.gradle.kts
  app/libs/oauth-5.9.1.aar
  app/src/main/java/com/kpaas/plog/PlogApp.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/LoginScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/LoginViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ⭐ [FEAT], 🐱 가을

#25 [Feature/#24] : 리워드 UI 및 커스텀 다이얼로그 구현
  .idea/misc.xml
  .idea/other.xml
  app/build.gradle.kts
  app/src/main/java/com/kpaas/plog/PlogApp.kt
  app/src/main/java/com/kpaas/plog/core_ui/component/PlogDialog.kt
  app/src/main/java/com/kpaas/plog/domain/entity/RewardListEntity.kt
  app/src/main/java/com/kpaas/plog/presentation/main/screen/MainScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/screen/ProfileScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportWriteScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/reward/screen/RewardScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/reward/screen/RewardViewModel.kt
  app/src/main/java/com/kpaas/plog/util/ContextExt.kt
  app/src/main/res/drawable/ic_reward_bronze_medal.png
  app/src/main/res/drawable/ic_reward_gold_medal.png
  app/src/main/res/drawable/ic_reward_seed.png
  app/src/main/res/drawable/ic_reward_silver_medal.png
  app/src/main/res/drawable/ic_reward_sprout.png
  app/src/main/res/drawable/ic_reward_tree1.png
  app/src/main/res/drawable/ic_reward_tree2.png
  app/src/main/res/drawable/ic_reward_tree3.png
  app/src/main/res/drawable/ic_reward_tree4.png
  app/src/main/res/drawable/ic_reward_tree5.png
  app/src/main/res/drawable/ic_reward_tree6.png
  app/src/main/res/drawable/ic_toast_star.xml
  app/src/main/res/drawable/toast_background.xml
  app/src/main/res/font/font_pretendard_bold.xml
  app/src/main/res/font/font_pretendard_medium.xml
  app/src/main/res/font/font_pretendard_regular.xml
  app/src/main/res/font/font_pretendard_semibold.xml
  app/src/main/res/layout/custom_toast.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearances.xml
Labels: 💟 [UI], 🐱 가을

#27 [Feature/#26] : 자동 로그인 및 로그아웃 기능 구현
  app/src/main/java/com/kpaas/plog/app/di/UserPreferencesModule.kt
  app/src/main/java/com/kpaas/plog/data/datasource/UserPreferencesDataSource.kt
  app/src/main/java/com/kpaas/plog/data/datasourceimpl/UserPreferencesDataSourceImpl.kt
  app/src/main/java/com/kpaas/plog/data/repositoryimpl/UserPreferencesRepositoryImpl.kt
  app/src/main/java/com/kpaas/plog/domain/repository/UserPreferencesRepository.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/LoginScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/LoginViewModel.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/navigation/ProfileNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/screen/ProfileScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/splash/SplashScreen.kt
Labels: ⭐ [FEAT], 🐱 가을

#30 [Feature/#28] : 백스택 정리
  app/src/main/java/com/kpaas/plog/presentation/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/LoginScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/auth/screen/SignupScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/main/screen/MainScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/navigation/PloggingNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/navigation/PloggingNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/plogging/screen/CertificationScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/navigation/ReportNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/ReportWriteScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/splash/SplashScreen.kt
Labels: ♻️ [REFACTOR], 🐱 가을

#31 [Feature/#29] : 신고내역 페이지 UI 구현
  app/src/main/java/com/kpaas/plog/domain/entity/MyReportListEntity.kt
  app/src/main/java/com/kpaas/plog/presentation/navigator/PlogNavHost.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/navigation/ProfileNavigator.kt
  app/src/main/java/com/kpaas/plog/presentation/profile/screen/ProfileScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/navigation/ReportNavGraph.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/MyReportScreen.kt
  app/src/main/java/com/kpaas/plog/presentation/report/screen/MyReportViewModel.kt
  app/src/main/res/drawable/ic_my_report_back.xml
  app/src/main/res/values/strings.xml
Labels: 💟 [UI], 🐰 윤지
